### ISSUE TITLE
Feature request: translate only text.

### ISSUE THREAD

**Issue by gustavosmendes** [kelciour/google-translate#16]
Hello!

I would like to suggest this feature: if I have a field with text and image, the option to translate only the text would be useful. 

Thank you for your effort.

**Comment by kelciour** [comment]
If I understood it correctly, it should be already possible with `Format` set to `Text`.

Format: **Text**

![изображение](https://user-images.githubusercontent.com/16260735/133719683-cea01a5e-3c88-470c-9963-f9c68c39568d.png)

Format: **HTML**

![изображение](https://user-images.githubusercontent.com/16260735/133719834-1ec3a7d4-2307-4d3c-a979-5d405938f5d3.png)

**Comment by gustavosmendes** [comment]
Sorry. I meant in the aspect of translating the text and ignoring the image. Also, I noticed there are differences in translation of some cards when selected to keep html or ignore. Lastly, html translation has ignored the hints. Is there anything that can be done?
![image](https://user-images.githubusercontent.com/87918773/133721016-9531701d-2a96-4860-8dd4-cd374d3cf620.png)

![image](https://user-images.githubusercontent.com/87918773/133721226-c172af15-947d-4604-a2a2-bb7fc25e66c1.png) - translate with html

![image](https://user-images.githubusercontent.com/87918773/133721259-7cf0f8ec-2736-4c65-a6df-d4e63ccf6605.png)
 translate only text
 
 This represents two contexts, the one with "text only" being more trustworthy in the sense. This behavior occurs with other cards. For this reason I thought of translating "text only", ignoring other sentences.
 
 Edit: HTML translation reminds Yoda speaking.

**Comment by kelciour** [comment]
I'm sorry but I don't quite understand. "Format: Text" will translate the text and ignore the image (and all other HTML tags).

If you want to use "Format: HTML" (to keep some HTML formatting like colors or bold text) but remove the image from the translated text, I'm not sure the add-on can do it. One possible option is to use Find and Replace with regular expressions from the card browser to replace something like <img.*?> with nothing. Or maybe keep the image in the translated field but hide it during review with some CSS in the Styling section of the card template like https://www.w3schools.com/css/tryit.asp?filename=trycss_display_none

Yes, the implementation of HTML translation is kind of naive as there no option on https://translate.google.com/ to translate as HTML and it was implemented by sending HTML to translate instead of text, it was good enough on a few tests to include it in the add-on (not this time) but it's better to translate as text.

![изображение](https://user-images.githubusercontent.com/16260735/133726984-3c625787-45ef-4ba7-b13c-0558a9218140.png)

![изображение](https://user-images.githubusercontent.com/16260735/133729296-737dc811-84b5-4901-b2a1-511f9a3063db.png)

A possible solution might be to somehow translate HTML with Chrome (#15) as it seems to work well.

![изображение](https://user-images.githubusercontent.com/16260735/133727736-5a93e776-554f-4216-9323-85f28070cfd5.png)

![изображение](https://user-images.githubusercontent.com/16260735/133727644-ec22c0d5-efb5-4fec-9ef0-0f94cd14feb9.png)

Another possible option is to add support for Google Cloud Translation API - https://cloud.google.com/translate/

About translating hints, I created a new issue - https://github.com/kelciour/google-translate/issues/17

**Comment by gustavosmendes** [comment]
Thank you for your effort. Last question: I'm currently trying to use the opposite: delete the text and keep only the <img> so I can use the advanced copy fields and translate into another field. I don't understand about codes or regex. Could you tell me how I would avoid it? I've searched a lot and I have failed.  e.g. I want to keep only the <img.*?> and delete the rest.

**Comment by kelciour** [comment]
I replied at https://forums.ankiweb.net/t/help-with-regex/13433
