### ISSUE TITLE
[Feature suggestion] Fetch definition of word, instead of translating it?

### ISSUE THREAD

**Issue by ghost** [kelciour/google-translate#2]
Is it possible to use this as a method of fetching the definition which includes example sentences?
If you translate any world in google translate it gives you synonyms and also the definition of the word including example sentences. Maybe it's a simple request change, I don't know. Would be very cool because when studying monolingually it sometimes is very hard to get good definitions for words. Anyways, it's a feature suggestion maybe.

**Comment by kelciour** [comment]
Thank you for the suggestion and closing the issue. I left it opened and didn't notify you after updating the add-on, because I came to the conclusion that examples that come with definitions are needed too, but I didn't add them.

I'd intended to add them today, but have no time left to do it and not sure when it'll be done.

**Comment by ghost** [comment]
You're right, I forgot about the examples. Would be cool if they could be fetched and inserted into a different field than the definition.
